emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: '{project-root}/../../../../common-types/resource-management'
    emit-lro-options: all
    emitter-output-dir: '{project-root}'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{version-status}/{version}/hanaonazure.json'
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armhanaonazure'
    fix-const-stuttering: true
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armhanaonazure
    service-dir: sdk/resourcemanager/hanaonazure
  '@azure-tools/typespec-java':
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-hanaonazure'
    flavor: azure
    namespace: com.azure.resourcemanager.hanaonazure
    service-name: HanaOnAzure
  '@azure-tools/typespec-python':
    api-version: 2020-02-07-preview
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-hanaonazure'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.hanaonazure
  '@azure-tools/typespec-ts':
    compatibility-lro: true
    emitter-output-dir: '{output-dir}/{service-dir}/arm-hanaonazure'
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: '@azure/arm-hanaonazure'
parameters:
  service-dir:
    default: sdk/hanaonazure
