emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: '{project-root}/../../../../common-types/resource-management'
    emit-lro-options: all
    emitter-output-dir: '{project-root}'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{version-status}/{version}/iothub.json'
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armiothub'
    fix-const-stuttering: false
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armiothub
    service-dir: sdk/resourcemanager/iothub
  '@azure-tools/typespec-java':
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-iothub'
    flavor: azure
    namespace: com.azure.resourcemanager.iothub
    service-name: IotHub
    use-object-for-unknown: true
  '@azure-tools/typespec-python':
    api-version: 2025-08-01-preview
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-iothub'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.iothub
  '@azure-tools/typespec-ts':
    compatibility-lro: true
    emitter-output-dir: '{output-dir}/{service-dir}/arm-iothub'
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: '@azure/arm-iothub'
parameters:
  service-dir:
    default: sdk/iothub
