emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: '{project-root}/../../../../common-types/resource-management'
    emit-lro-options: all
    emitter-output-dir: '{project-root}'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{version-status}/{version}/openapi.json'
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armdatamigration'
    fix-const-stuttering: true
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armdatamigration
    service-dir: sdk/resourcemanager/datamigration
  '@azure-tools/typespec-java':
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-datamigration'
    flavor: azure
    namespace: com.azure.resourcemanager.datamigration
    service-name: DataMigration
  '@azure-tools/typespec-python':
    api-version: 2025-09-01-preview
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-datamigration'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.datamigration
  '@azure-tools/typespec-ts':
    compatibility-lro: true
    emitter-output-dir: '{output-dir}/{service-dir}/arm-datamigration'
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: '@azure/arm-datamigration'
parameters:
  service-dir:
    default: sdk/datamigration
